name: Run Integration Tests

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string

env:
  PROJECT_PATH: ./${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.Tests.Integration/Tatum.CSharp.${{ inputs.name }}.Tests.Integration.csproj
  GITHUB_GIST_ID: 7c96c30e8017c8dfb57b88e323f8114b

jobs:
  integration_tests:
    name: ${{ inputs.name }} - Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: ${{ inputs.name }} - Bump Version
      run: dotnet add ${{ env.PROJECT_PATH }} package Tatum.CSharp.${{ inputs.name }} --no-restore --version ${{ inputs.version }}
    - name: ${{ inputs.name }} Integration Test - Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: ${{ inputs.name }} Integration Test - Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    - name: ${{ inputs.name }} Integration Test - Run Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx"
      continue-on-error: true
      env:
        TEST_DATA: ${{ secrets.TEST_DATA }}
        INTEGRATION_TEST_APIKEY: ${{ secrets.INTEGRATION_TEST_APIKEY }}
    - name: Gather test results
      id: get-test-results
      run: |
          echo "passed=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Passed"[^<]*(?=>)' ./${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.Tests.Integration/TestResults/test-results.trx | wc -l)" >> $GITHUB_OUTPUT
          echo "failed=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Failed"[^<]*(?=>)' ./${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.Tests.Integration/TestResults/test-results.trx | wc -l)" >> $GITHUB_OUTPUT
          echo "skipped=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Skipped"[^<]*(?=>)' ./${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.Tests.Integration/TestResults/test-results.trx | wc -l)" >> $GITHUB_OUTPUT
    - name: Update passed counter value
      uses: ./.github/actions/counters
      with:
        gistId: ${{ env.GITHUB_GIST_ID }}
        gistFileName: csharp-sdk-test-counters.json
        action: addValue
        counterName: ${{ inputs.name }}
        counterValue: ${{ steps.get-test-results.outputs.passed }}
        gistSecret: ${{ secrets.GIST_SECRET }}
    - name: Update failed counter value
      uses: ./.github/actions/counters
      with:
        gistId: ${{ env.GITHUB_GIST_ID }}
        gistFileName: csharp-sdk-test-counters-failed.json
        action: addValue
        counterName: ${{ inputs.name }}
        counterValue: ${{ steps.get-test-results.outputs.failed }}
        gistSecret: ${{ secrets.GIST_SECRET }}
    - name: Update skipped counter value
      uses: ./.github/actions/counters
      with:
        gistId: ${{ env.GITHUB_GIST_ID }}
        gistFileName: csharp-sdk-test-counters-skipped.json
        action: addValue
        counterName: ${{ inputs.name }}
        counterValue: ${{ steps.get-test-results.outputs.skipped }}
        gistSecret: ${{ secrets.GIST_SECRET }}
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Report
        path: ./${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.Tests.Integration/TestResults/test-results.trx
        reporter: dotnet-trx
