name: Post release integration tests
run-name: ${{ inputs.version }} - post release tests

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Test_Chains:
    strategy:
      matrix:
        arrays: [
          { chain: "Ethereum", dependsOn: "Evm.Local" },
          { chain: "Bitcoin", dependsOn: "Bitcoin.Local" },
          { chain: "Nft", dependsOn: "Evm.Local" },
        ]
    name: Test Packages
    uses: ./.github/workflows/integrationTests.yml
    with:
      name: ${{ matrix.arrays.chain }}
      version: ${{ inputs.version }}
    secrets: inherit
