name: SlackNotification
run-name: ${{ inputs.version }} - slack notification

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Slack_Notification:
    name: Post to a Slack channel
    if: ${{ !contains(inputs.version, 'rc') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: C03VAV2D601
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
